Добавляю графику
htmlacademy-htmlcss/2103309-gllacy-35 pull request #3
Opened 2022-10-02 15:58 UTC by MrsGermy

2022-10-03 11:06 UTC, Dima-Dim requested changes
https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03

2022-10-03 11:06 UTC, Dima-Dim commented on index.html
> +          <svg width="12" height="7" fill="none" xmlns="http://www.w3.org/2000/svg">
https://htmlacademy.ru/blog/html/content-or-decor-img

2022-10-04 06:09 UTC, Dima-Dim requested changes
https://htmlacademy-htmlcss.github.io/2103309-gllacy-35/3/ - нужно бы решить проблему с загрузкой изображений.

2022-10-04 16:06 UTC, MrsGermy commented
Я так поняла, что проблема была не в пути, а в именах картинках. Путь был указан у всех правильно. После первого пулреквеста я их переименовала по правилам, а тут они остались со старыми именами, поэтому не загрузились...

2022-10-05 04:20 UTC, Dima-Dim commented
> Я так поняла, что проблема была не в пути, а в именах картинках. Путь был указан у всех правильно. После пулреквеста и первой проверки я их переименовала, а тут они остались со старыми именами, поэтому не загрузились... Попробуем еще раз...

Названия файлов это тоже часть пути :) да не относительная и не абсолютная, но часть.

2022-10-05 05:07 UTC, merged