Стилизация страниц
htmlacademy-htmlcss/2103309-gllacy-35 pull request #5
Opened 2022-10-08 14:13 UTC by MrsGermy

По моему я опять начала торопиться, но получается очень вкусно, мороженки это хорошо.)) главное что бы ошибок было немного :)

2022-10-10 11:37 UTC, Dima-Dim requested changes
Не использовать "visually_hidden" там где нет доступного скрытия и подразумевается добавление и удаление класса скрывающего элемент.
Поправить форматирования для лучшей читаемости.

2022-10-10 11:37 UTC, Dima-Dim commented on styles/styles.css
> +margin: 0 auto;
Что за беда с отступами? :)

2022-10-10 11:37 UTC, Dima-Dim commented on styles/styles.css
> +.main_header .visually_hidden {
"visually_hidden" это сам по себе паттерн для доступного скрытия. Для иных целей его использовать не нужно.

2022-10-10 11:37 UTC, Dima-Dim commented on styles/styles.css
> +
Для чего эти пустые строки?

2022-10-11 03:44 UTC, Dima-Dim commented on catalog.html
> +          <li class="user_login_item ">
Для чего тут появился пробел? :)

2022-10-11 03:44 UTC, Dima-Dim commented on catalog.html
>    <img src="images/logo.svg" width="137" height="56" alt="Logo of GllacyShop.">
img и следующие теги ведь внутри header, но у строк отступ такой же как у header.

2022-10-11 03:44 UTC, Dima-Dim commented on catalog.html
> +            <div class="user_login_active">
После этого `div`-а тоже пошли вложенные теги, но строки на том же уровне.

2022-10-11 03:44 UTC, Dima-Dim commented on styles/styles.css
> +.delivery_description,.delivery_form_text {
То, что после запятой, нужно перенести на новую строку.

2022-10-11 03:44 UTC, merged

2022-10-11 03:50 UTC, MrsGermy commented
Обязательно учту замечания, поправлю.  Одно исправляешь, про другое забываешь. Вот что значит профессионал проверяет, все недочеты сразу видно… :)