Завершение верстки
htmlacademy-htmlcss/2103309-gllacy-35 pull request #9
Opened 2022-10-23 07:49 UTC by MrsGermy

2022-10-24 05:12 UTC, Dima-Dim requested changes
https://htmlacademy-htmlcss.github.io/2103309-gllacy-35/9/ в консоли есть информация о не загрузившихся ресурсах. Хорошо бы это исправить, в месте с остальными замечаниями.

2022-10-24 05:12 UTC, Dima-Dim commented on catalog.html
> +            <ul class="catalog_list ">
Почему появился лишний пробел после названия класса?

2022-10-24 05:12 UTC, Dima-Dim commented on catalog.html
> +                <ul class="user_card_list">
Почему у `ul` отступ? Он же не вложен в `h2`.

2022-10-24 05:12 UTC, Dima-Dim commented on catalog.html
> +                        <button class="user_card_item_btn" type="button">
Тоже странный отступ у `button`.

2022-10-24 05:12 UTC, Dima-Dim commented on catalog.html
> +                  <button type="button" class="range_switch range_switch_min"></button>
https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-02

2022-10-24 05:12 UTC, Dima-Dim commented on index.html
> +        <div class="slider_item_picture">
Для чего изображению обёртка?

2022-10-24 05:12 UTC, Dima-Dim commented on index.html
> +          <p class="offer_list_description">При покупке 2 кг пломбира добавим в ваш заказ упаковку нежных<br>>зефирок совершенно бесплатно.</p>
Одна `>` лишняя.

2022-10-24 05:12 UTC, Dima-Dim commented on index.html
> +      <a class="blog_new_title" href="new.html">10 способов сервировки<br>фруктовых щербетов<br>к столу</a>
Ну от одного `br` точно можно избавиться.

2022-10-24 05:12 UTC, Dima-Dim commented on styles/styles.css
> +  margin-top: 8.15px;
Не нужны ту не сотые не десятые. Целых должно быть достаточно.

2022-10-24 05:12 UTC, Dima-Dim commented on styles/styles.css
> +  left: -20px;
А не понятнее было бы блоку просто задать ширину?
И в целом если рассматривать подход с контейнером для кнопок, то он перекрывает изображение. В данном случае это не заметно, потому что взаимодействия с изображением нет, но в целом, делать так не универсально.

2022-10-24 18:26 UTC, MrsGermy commented
Ошибки поправила (какие всё же глупые :) ), картинки отображаются,  у слайдера кнопки переделала - убрала вообще у них обертку, что бы не перекрывать картинку.
А у макета криво сделана картинка  большой мороженки и подложки... попросить бы дизайнеров переделать :)

2022-10-25 05:41 UTC, Dima-Dim commented
> А у макета криво сделана картинка большой мороженки и подложки... попросить бы дизайнеров переделать :)

Можно написать авторам об этом.

2022-10-25 07:14 UTC, merged